### ISSUE TITLE
Conflict with org-src-tab-acts-natively

### ISSUE THREAD

**Issue by Yevgnen** [joaotavora/yasnippet#761]
With the minimal `.emacs`

```
(package-initialize)
(setq org-src-tab-acts-natively t)
(require 'org)
(require 'yasnippet)
(yas-global-mode 1)
```
placing the cursor in an org source block, and <kbd>TAB</kbd>, yasnippet keep alerting 
```
yas--fallback: yasnippet fallback loop!
This can happen when you bind ‘yas-expand’ outside of the ‘yas-minor-mode-map’.
```
The issue is gone if `org-src-tab-acts-natively` is set to `nil`.

Emacs version:`GNU Emacs 25.1.1 (x86_64-apple-darwin16.1.0, Carbon Version 157 AppKit 1504.6) of 2016-11-02`

Org version: `Org mode version 9.0.1 (9.0.1-elpa @ /Users/user/.emacs.d/elpa/org-20161118/)`

Yasnippet version: `yasnippet-20161202.1700 Version: 0.11.0`

---
[ *npostavs* -- added summary ] 

- [x] `yas--fallback: yasnippet fallback loop!`
  - Will be fixed by #760.
- [X] `TAB` on first word of line jumps to end of block instead of
expanding snippet.
  - Caused by org-cdlatex-mode, not a yasnippet issue. https://github.com/joaotavora/yasnippet/issues/761#issuecomment-267537523, https://github.com/joaotavora/yasnippet/issues/761#issuecomment-267695648
  - may also be solvable by adding to `org-tab-first-hook`
- [x] org-mode snippets override source block mode snippets with the
same key
  - [x] Can be solved with the condition system: https://github.com/joaotavora/yasnippet/issues/761#issuecomment-267701377
  - [X] ~~Or add `yas-org-tab-try-expand` to `org-tab-first-hook`  https://github.com/joaotavora/yasnippet/issues/761#issuecomment-267743447~~ this was wrong
    - ~~TODO: add `yas-org-tab-try-expand` or similar to yasnippet~~
- [x] Interative snippet features (e.g., field updates) don't work in org source blocks
  - Because they're expanded in a temp buffer that's killed immediately. https://github.com/joaotavora/yasnippet/issues/761#issuecomment-267742580
  - Also fixing in #760.

**Comment by npostavs** [comment]
Can you check if #760 fixes this?

And if not, can you expand your report a bit for someone unfamiliar with how org mode source blocks look/work.

**Comment by Yevgnen** [comment]
Thanks for you reply. I've tried the commit, the alter seems gone. The origin issue happens when using a tab to indent the code in a org source code block where the cursor is denote by `I`
```
#+BEGIN_SRC emacs-lisp :exports none
I(print "aha")
#+END_SRC
```
Checking the `TAB`, it is bound to `yas-expand`.

The new commit seems fixes this, but with a bit strange behavior. Firstly, I have a snippet `(message $1)` which is bound to `m` is the shortcut for expanding. Under this commit, when the cursor is right after `m`
```
#+BEGIN_SRC emacs-lisp :exports none
mI
#+END_SRC
```
tapping `TAB` moves the cursor to `#+END_SRCI`, right after `SRC`. But if the cursor is right after some lisp code 
```
#+BEGIN_SRC emacs-lisp :exports none
(print "aha")mI
#+END_SRC
```
tapping `TAB` expands the snippet. In these two situation, checking the `TAB` under the new commit gives `org-cycle`. Please see the gif for illustration.

![yas](https://cloud.githubusercontent.com/assets/16749790/21102676/164a21ca-c0ba-11e6-91fd-099e087b5815.gif)

**Comment by npostavs** [comment]
> Firstly, I have a snippet `(message $1)` which is bound to `m` is the shortcut for expanding.

Is this an emacs-lisp snippet, or an org-mode snippet?

**Comment by Yevgnen** [comment]
An emacs-lisp snippet.

**Comment by npostavs** [comment]
Huh. Does that mean #649 somehow got magically implemented without me noticing, or do you have some extra configuration to make this work?

**Comment by Yevgnen** [comment]
I guess it is `org-src-tab-acts-natively`, for a emacs lisp snippet will not expand without going into [`org-source-lang-mode`](http://orgmode.org/manual/Editing-source-code.html#Editing-source-code) if it is  set to `nil`. It makes TAB acts like natively.

**Comment by npostavs** [comment]
> tapping TAB moves the cursor to #+END_SRCI, right after SRC

I can't reproduce this, the snippet gets expanded for me in this case, although the `$1` doesn't seem to be handled properly. Might be a similar problem as #742.

I get different behaviour with 8.2.10 (the one that comes builtin with Emacs 25.1): the `org-src-tab-acts-natively` option seems to have no effect whatsoever (doesn't even indent lisp code).

**Comment by Yevgnen** [comment]
Sorry for late reply. There seems some other conflicts in my configs. The commit #760 seems fixed the origin issue.

**Comment by Yevgnen** [comment]
But I have another question. 

> Firstly, I have a emacs-lisp snippet (message $1) which is bound to `m` is the shortcut for expanding. 

If there's **no** org snippet having trigger key `m`, the snippet will expand to `(message $1)` in the source code block as expected.

If there's **another** org snippet have trigger key `m`, in the source block, the snippet will expand to the org one.

But! I've tested and find that 

1. Any other emacs-lisp snippet that has no conflict key with any org snippet will correctly expand inside the source code block
2. Any other org snippet that has no conflict key with any emacs-lisp snippet will correctly expand outside the source code block. 

Based on this observation, I think the snippet inside source block should expand in emacs-lisp way and org way outside.

But currently the result is 
1. If there's only org snippet, it will expand everywhere.
2. If there's only emacs-lisp snippet, it will expand only inside the block.
3. If there are both, the org snippet will expand even inside the block.

How to you think about this ? Thanks !

**Comment by npostavs** [comment]
> Based on this observation, I think the snippet inside source block should expand in emacs-lisp way and org way outside.

If we can manage that, then it would be ideal, yes.

> I've figured out that it's conflict with `org-cdlatex-mode`. Enabling `org-cdlatex-mode` will cause the snippet can not expand and move the cursor away to `#+END_SRCI`.

Additionally this requires with org 9.0.2 to reproduce.

---

> I get different behaviour with 8.2.10 (the one that comes builtin with Emacs 25.1): the `org-src-tab-acts-natively` option seems to have no effect whatsoever (doesn't even indent lisp code).

It seems that in org 8.x `org-src-tab-acts-natively` requires `org-src-fontify-natively` to also be set, otherwise it has no effect.

**Comment by npostavs** [comment]
> > I've figured out that it's conflict with `org-cdlatex-mode`. Enabling `org-cdlatex-mode` will cause the snippet can not expand and move the cursor away to `#+END_SRCI`.
> 
> Additionally this requires with org 9.0.2 to reproduce.

Org 8.x puts `org-src-native-tab-command-maybe` into `org-tab-first-hook`, but org 9.x seems to have removed this function, so `cdlatex-tab` overrides the tab command in this case. Nothing to be done about it from yasnippet's side.

**Comment by npostavs** [comment]
> > Based on this observation, I think the snippet inside source block should expand in emacs-lisp way and org way outside.
> 
> If we can manage that, then it would be ideal, yes.

This can be implemented by the [condition](http://joaotavora.github.io/yasnippet/snippet-expansion.html#sec-2-2) system. Add `# condition: (not (org-in-src-block-p t))` to your org snippets, or 
```elisp
(add-hook 'org-mode-hook
          (lambda () (setq yas-buffer-local-condition '(not (org-in-src-block-p t)))))
```
to your init file to apply this to all org-mode snippets.

**Comment by npostavs** [comment]
> the snippet gets expanded for me in this case, although the $1 doesn't seem to be handled properly.

The problem is that org performs the all the editing in a temporary buffer. So the snippet gets expanded and then the buffer is killed. Hence, only the initial expansion makes it back into the org source block. There might be some way for yasnippet to hack around this.

**Comment by Yevgnen** [comment]
> I've figured out that it's conflict with org-cdlatex-mode. Enabling org-cdlatex-mode will cause the 
> snippet can not expand and move the cursor away to #+END_SRCI.

I've fixed this by advising `org-try-cdlatex-tab` yesterday.

> This can be implemented by the condition system. Add # condition: (not (org-in-src-block-p t)) to your org snippets, or
> (add-hook 'org-mode-hook
>          (lambda () (setq-local yas-buffer-local-condition '(not (org-in-src-block-p t)))))
> to your init file to apply this to all org-mode snippets.

Thanks for the information about this. But figuring out why the issue happens maybe important though.

So the left issue is about the `$1`. Thanks for you works~

**Comment by npostavs** [comment]
> But figuring out why the issue happens maybe important though.

Oh, I know why it happens: org tries commands bound to `<tab>` in the current buffer `org-mode` first, and then switches to the sub-buffer in `emacs-lisp-mode` to implement the "native tab" thing.

**Comment by Yevgnen** [comment]
So when `org-src-tab-acts-natively` is set to `t`, maybe it's an `org` issue should try the 'native tab' first ? I've looked into `org-cycle`, it tries too many conditions.😂

**Comment by npostavs** [comment]
> maybe it's an org issue should try the 'native tab' first ?

As far as I can tell, org 8.x *does* try "native tab" first. I guess org devs decided that was a bad idea, because they changed it in 9.x. It looks like you could add this function to `org-tab-first-hook`:

```elisp
(defun yas-org-tab-try-expand ()
  "Add this to `org-tab-first-hook'."
  (when (and yas-minor-mode (yas--templates-for-key-at-point))
    (yas-expand)
    t))
```

**Comment by npostavs** [comment]
@Yevgnen can you try out the code in #760? It's a bit messy right now, but it seems to be working for me.

**Comment by Yevgnen** [comment]
I've been using  #760 for weeks with the workaround

```
(add-hook 'org-mode-hook
          (lambda () (setq-local yas-buffer-local-condition '(not (org-in-src-block-p t)))))
```

 above, the origin issue is fixed, I confirm. I pulled and tried the latest commit, does it fix the `$1` issue ? The `$1` issue is still here in org 9.0.3. If the `$1` issue is not related to the pull request, I'll close this one and thanks for all your works.

**Comment by npostavs** [comment]
> I confirm. I pulled and tried the latest commit, does it fix the $1 issue ? The $1 issue is still here in org 9.0.3.

Ah, it fixes it with org 8.2, but not with 9.0.3, they've changed some variable names. I pushed some more commits to deal with that, and also the control overlay wasn't being moved correctly. Please try again.

**Comment by Yevgnen** [comment]
Sorry for late reply. The newest commit still does not work well with `$` here with `Org mode version 9.0.3 (9.0.3-elpa @ /Users/user/.emacs.d/elpa/org-20161224/)` and `GNU Emacs 25.1.1 (x86_64-apple-darwin16.3.0, Carbon Version 157 AppKit 1504.76) of 2016-12-23`. Also, under this commit, the `TAB` seems become a bit lag when before  expanding the snippe.

**Comment by npostavs** [comment]
> The newest commit still does not work well with `$` here

Ah, I had a silly mistake, not sure how I missed that one. Should be fixed now.

> Also, under this commit, the TAB seems become a bit lag when before expanding the snippet.

Hmm, not seeing it here. Can you post the results of doing `M-x profiler-start RET RET` (choosing default `cpu` mode) `TAB` `M-x profiler-report RET`?

**Comment by Yevgnen** [comment]
The lag problem seems my own issue. But there still some problem of the `$1`, i.e., goes to the wrong position.

![yas](https://cloud.githubusercontent.com/assets/16749790/21560230/c132b7c0-ce96-11e6-9ecc-722e14694871.gif)

The snippet is 

```
# -*- mode: snippet -*-
# name: tfdg
# key: tfdg
# group : general
# --
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("${1:/tmp/data/}", one_hot=True)

X_train = mnist.train.images
Y_train = mnist.train.labels
X_test = mnist.test.images
Y_test = mnist.test.labels
$0
```

**Comment by npostavs** [comment]
Ah, another difference in org 8.x to 9.x, looks like the indentation happens at a different time or something. I switched from saving character positions to line numbers which seems to fix the problem.

**Comment by Yevgnen** [comment]
Hi, sorry for late reply. The issue is almost gone. I often use `org-edit-special` which bound to `C-c '` by default to edit the source code block. After exiting the special editing, the code in the block is formatted to has two leading spaces for alignment in the org buffer. That is, if the code in the block starts with leading spaces, the `$` placeholder in empty line seems go to wrong position, where `n`(n=num of leading spaces) chars before the right position. Please see this example
![yas](https://cloud.githubusercontent.com/assets/16749790/21677714/4e5d2c78-d376-11e6-944d-972665dc0e63.gif)

The test snippet of the last line in fact contains `4+4` spaces before `$0`.

    # -*- mode: snippet -*-
    # name: test
    # key: test
    # --
    for ${1:i} in range($2):
        for ${3:j} in range($4):
            $0

**Comment by npostavs** [comment]
I think this is a bug in org 9.x, it doesn't preserve the leading spaces in blank lines:

![org-src-indent](https://cloud.githubusercontent.com/assets/287742/21688881/7a71baac-d33c-11e6-856b-b98aeab3155e.gif)

**Comment by Yevgnen** [comment]
Yes, it probably is. I haven't encounter other problem right now under this commit. Thank you.

**Comment by npostavs** [comment]
Thanks for your help! I've cleaned up and rebased #760 now, I will push to master sometime this week.

**Comment by DiogoFerrari** [comment]
Was this fixed? I still can't expand inside code blocks.

**Comment by npostavs** [comment]
@DiogoFerrari I think it was fixed, but then broke again on a newer org version, see #852.

**Comment by dericbytes** [comment]
I was getting the [[:space:]] missing error too when using yas-expand was done an org block. But these comments helped me stop it.

This line org-mode setting that was causing it was

`(setq org-src-tab-acts-natively t)`

and adding this line as well

`(setq org-edit-src-content-indentation 4)`

stopped an error being invoked and now I  get a message instead.

`Can’t guess python-indent-offset, using defaults: 4`

org 9.1.5
yas version 0.13.0  - 2018 with cl-lib 0.5
GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.24) of 2017-11-09

**Comment by dericbytes** [comment]
It is not fixed. I did not get the error message because I changed the org lang to 'python'. I get the error message only when I have the lang set to 'emacs-lisp'

`Warning (yasnippet): Couldn’t find: "[[:space:]
]*\"[[:space:]
]*\\(\\)[[:space:]
]*\""
`

**Comment by dericbytes** [comment]
see https://github.com/joaotavora/yasnippet/issues/976 for a hack to get yas-expand to work in a org src block when `org-src-tab-acts-natively' is set to true
