### ISSUE TITLE
Quoting backticks not working

### ISSUE THREAD

**Issue by cjk** [joaotavora/yasnippet#800]
If I create a snippet like so:

```
#name: Markdown-Codeblock
#key: code_
# --
\`\`\`${1:javascript}
$0
\`\`\`
```

It get's expanded to this:
```
YASESCAPE96PROTECTGUARDYASESCAPE96PROTECTGUARDYASESCAPE96PROTECTGUARDjavascript

YASESCAPE96PROTECTGUARDYASESCAPE96PROTECTGUARDYASESCAPE96PROTECTGUARD
```

I was expecting to see a markdown backtick-codeblock. What am I doing wrong?

**Comment by cjk** [comment]
Related, but proposed solution doesn't work: http://stackoverflow.com/questions/42613304/backticks-in-snippets-for-emacs

**Comment by npostavs** [comment]
What version of yasnippet are you using? This seems to be fixed in HEAD.

**Comment by cjk** [comment]
I'm using the latest git-version. yas-about says `yasnippet (version 0.11.0) -- pluskid/joaotavora/npostavs`

**Comment by npostavs** [comment]
Hmm, works for me. Emacs version 25.2 (I also tried with 26.0.50), yasnippet version 5043a961215158619199cf03a85a0c063a28c644.

I did `emacs -Q -L markdown-mode/ -l markdown-mode.el -L yasnippet/ -l yasnippet.el -f yas-global-mode -f markdown-mode`, `M-x yas-new-snippet`, copied your snippet text above, `C-c C-l` to load it, switch back `*scratch*`, enter `_code`, hit `tab`, result:

````markdown
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with C-x C-f and enter text in its buffer.

```javascript

```
````

**Comment by npostavs** [comment]
> yas-about says `yasnippet (version 0.11.0) -- pluskid/joaotavora/npostavs`

I really have to make that function give more info...

**Comment by cjk** [comment]
Thanks for looking into this so quickly! Indeed it seems to work on your side and perhaps is a configuration problem on my side. I'll try to replicate and diagnose the problem with my setup and then report back here.
I'm using company-yassnippet and perhaps other libraries that may influence yasnippets' behaviour.

**Comment by cjk** [comment]
OK after updating some libs + restarting emacs I was no longer able to reproduce the above error - yasnippet works as intended. Thanks for your help @npostavs !

**Comment by npostavs** [comment]
>> yas-about says `yasnippet (version 0.11.0) -- pluskid/joaotavora/npostavs`
>
> I really have to make that function give more info...

Done ca04f69c101cff4fd6e71a4c1642e3a169a0057b. It should now say something like `yasnippet (version 0.11.0-snapshot20170407.2224) -- pluskid/joaotavora/npostavs` for MELPA installs.

**Comment by npostavs** [comment]
Based on discussion in https://emacs.stackexchange.com/questions/32417/yasnippet-for-markdown-code-block, it's possible something can mess up yasnippet's escaping and that restarting Emacs merely hides the bug. If this starts happening again, please try instrumenting `yas--snippet-parse-create` with edebug and stepping through it.

**Comment by DirkSchmitt** [comment]
I think this issue is not fixed.
Today I run in this problem. Emacs restart mitigated it.

Software version.
> ```yasnippet (version 0.12.2) -- pluskid/joaotavora/npostavs```
> ```elpa-yasnippet         0.12.2-1~ubuntu16.04.1~c42.ppa1```

Before the problem occured, I have written a snippet and make the following (non-lisp-hero) mistakes
- use of ' instead "
- balancing errors of `

After fixing these problems the \$BASH phrase was expanded in the broken way.
Restart has mitigated the problem.

**Comment by npostavs** [comment]
> I think this issue is not fixed.

Indeed, the problem is, everyone hitting this restarts to make it go away before we can investigate. That's why you shouldn't restart until-

> Today I run in this problem. Emacs restart mitigated it.

Oh. Too late. :/

**Comment by DirkSchmitt** [comment]
1. **non-lisp-hero**
2. Seen this bug report after mitigating my *work problem*

But If the steps are documented, which I should take after reproducing the problem, I will try it.

**Comment by npostavs** [comment]
Yeah, it's a tough problem. Also, I'm not entirely sure what steps would be needed since I don't know exactly what the bug is. My suggestion is to instrument `yas--snippet-parse-create` with edebug (find the function in `yasnippet.el` and then hit <kbd>C-u C-M-x</kbd> when point is on the function). Then when you expand a snippet Emacs will pause in `yas--snipet-parse-create`. Jumping down to the `yas--restore-escapes` call would probably be the relevant part (move point down to the beginning of that line, then press <kbd>h</kbd> to advance the code there). Then press <kbd>i</kbd> to step into the function, <kbd>SPC</kbd> to advance through it. The `YASESCAPE96PROTECTGUARD` should be removed by the end of that function call...

```elisp
    (yas--restore-escapes)        ; Restore escapes.
```

**Comment by DirkSchmitt** [comment]
Done, on step through the following code:
```
(defun yas--restore-backquotes ()
  "Replace markers in `yas--backquote-markers-and-strings' with their values."
  (while yas--backquote-markers-and-strings
    (let* ((marker-and-string (pop yas--backquote-markers-and-strings))
           (marker (car marker-and-string))
           (string (cdr marker-and-string)))
      (save-excursion
        (goto-char marker)
        (save-restriction
          (widen)
          (delete-char -1)
          (insert string)
```
Here I got: 
> Wrong type argument: char-or-string-p, (})

The broken/faulty snippet is:
```
# -*- mode: snippet; require-final-newline: nil -*-
# name: copyLeft()
# key: copyLeft
# binding: direct-keybinding
# expand-env: ((yas-indent-line 'fixed) (yas-wrap-around-region 'nil))
# --
# ----------------------------------------------------------------------------------------------------------------------
function copyLeft() {
echo 'TEST ${5:`(format-time-string '%Y'}
echo "    [version: \${PRGVERSION} (\${PRGDATE})]"
}
```

**Comment by npostavs** [comment]
> Wrong type argument: char-or-string-p, (})

Is that `Wrong type argument: char-or-string-p, (})`, or `Wrong type argument: char-or-string-p, ("}")`?
I guess this error must be happening at the `(insert string)` line. What is the value of `yas--backquote-markers-and-strings`, during and after snippet expansion (use <kbd>e</kbd> to check value during the expansion, <kbd>M-:</kbd> or <kbd>f1 v</kbd> afterwards)?

**Comment by npostavs** [comment]
Okay, after playing around with the broken snippet a little and thinking about this, I believe I have understood what the problem is: `yas--save-backquotes` saves entries for every backquote into `yas--backquote-markers-and-strings` and `yas--restore-backquotes` pops them and applies them. That's all fine, assuming there are no errors in the snippet, but if there are errors then not all entries in `yas--backquote-markers-and-strings` would be removed, and those entries would cause errors in future snippet expansions, even if the new snippets are correct. For example, starting with:

````
# name: foo
# key: foo
# --
```${1:javascript}
$0
```
````

This fails to expand properly, producing `YYYYY` (with error `Wrong type argument: char-or-string-p, (end-of-file)`). But even after fixing it to

````
# name: foo
# name: foo
# key: foo
# --
\`\`\`${1:javascript}
$0
\`\`\`
````

that still fails to expand properly, producing
```
YASESCAPE96PROTECTGUARDYASESCAPE96PROTECTGUARDYASESCAPE96PROTECTGUARDjavascript

YASESCAPE96PROTECTGUARDYASESCAPE96PROTECTGUARDYASESCAPE96PROTECTGUARD
```
(with error `Wrong type argument: char-or-string-p, (${1:javascript})`). Although if you expand two more times, it does finally work after all entries are popped off `yas--backquote-markers-and-strings`.

**Comment by joaotavora** [comment]
Seems to be a case for simply resetting `yas--backquote-markers-and-strings`?

**Comment by npostavs** [comment]
I think it would be preferable to remove it entirely, it looks to me like the marker-and-string entries can be passed via return value and parameters.

**Comment by npostavs** [comment]
> I think it would be preferable to remove it entirely,

As seen in #895.
