### ISSUE TITLE
Undo of an expanded snippet does not work correctly if indentation was adjusted

### ISSUE THREAD

**Issue by fabacino** [joaotavora/yasnippet#821]
Steps to reproduce the bug:

``` bash
git clone --recursive https://github.com/joaotavora/yasnippet.git
cd yasnippet
emacs --version
  => GNU Emacs 25.2.1
git log -1 --oneline
  => 1043b6c Restore syntax-propertize-function before indenting mirrors
HOME="$PWD" emacs -L .
```

``` elisp
(require 'yasnippet)
(yas-global-mode 1)
(find-file "test.el")
```

Put the following contents into the file (cursor indicated by ^):
``` elisp
(let (a)
  (let (b)
(while s
        ^
```

After pressing TAB, the snippets gets correctly expanded into: 
``` elisp
(let (a)
  (let (b)
    (while (setq )
                 ^
```

However after an undo (`C-/`), the expansion is not reverted properly:
``` elisp
(let (a)
  (let (b)
    (whsile 
        ^
```

The bug only occurs if the expanded snipped is also indented. If the `while` in my example were indented correctly in the first place, the undo would work as well.
I assume this is the same bug @fikovnik was mentioning in issue https://github.com/joaotavora/yasnippet/issues/478#issuecomment-293885882.
Let me know if you need further information to reproduce the bug.

**Comment by npostavs** [comment]
Thanks for the report, I can confirm.

**Comment by npostavs** [comment]
Please try out #822.

**Comment by fabacino** [comment]
Works nicely, thank you.

**Comment by npostavs** [comment]
By the way, I'm wondering if it's correct that the snippet gets indented even though `yas-also-auto-indent-first-line` is `nil`.

It seems to have started happening in `0.10.0`. I guess it's related to #665 and #712.
 @joaotavora Do you think this is correct behaviour?

**Comment by longitude** [comment]
Hi @npostavs,

I can confirm the most recent commit broke yasnippets undo for JS-MODE 

I have a snippet with predefined indentation which I expand and hit undo the text following the snippet is cutoff. 

Single line snippets and multiple line snippets with no indentation work as expected.

I moved to previous build undoing recent changes, snippets with indentation work great.

**Comment by npostavs** [comment]
@longitude can you show exactly the snippet that breaks?

**Comment by longitude** [comment]
@npostavs 

```
# -*- mode: snippet -*-
# name: if
# key: if
# --
if ($1) {
  $0
}
```

**Comment by npostavs** [comment]
Sorry, I don't understand how to reproduce your problem, can you explain step by step?

**Comment by longitude** [comment]
![yasnippet-cutoff-next-line](https://cloud.githubusercontent.com/assets/5510191/26794499/e17a6c06-49ef-11e7-94ee-edc815a7555a.gif)

**Comment by npostavs** [comment]
Thanks, I see it now, I had been testing with a shorter line following the snippet so I didn't notice before.

**Comment by npostavs** [comment]
Should be fixed by #822.

**Comment by longitude** [comment]
#825 fix works

**Comment by npostavs** [comment]
Thanks for testing, I pushed to master

**Comment by longitude** [comment]
Sorry, after testing again with the latest build I still see this issue. I was able to fix when I rolled back to this commit 1043b6c557f39a38b14b7618c174d8c47e946c4a.

**Comment by npostavs** [comment]
Hmm, it's working for me. Are you sure you tested the latest build? Is there some particular text in the buffer required to trigger it? Does the test `undo-indentation-multiline` test I added not cover your scenario?

**Comment by longitude** [comment]
I got the latest update now and it works 👍

**Comment by deadtrickster** [comment]
Hi!
My yasnippet version is 20170923.1646. Still have this error.
![yasnippet-undo-bug](https://user-images.githubusercontent.com/172311/32920414-2cc3e194-cb3a-11e7-8003-fde0f1b42652.gif)

Mode is erlang. Should I switch to master?

**Comment by npostavs** [comment]
Could you open a new issue with all the details please. (Emacs version, where to get erlang-mode, snippet used, precise sequence of input).
